<a href="https://colab.research.google.com/github/PolyTheML/Pytorch_tutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**LISTS**

In [ ]:
my_list = [[1,2,3,4], [5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

# Numpy Arrays

In [ ]:
np1 = np.random.rand(3,4)

np1

array([[0.76329002, 0.1831159 , 0.20898667, 0.81264594],
       [0.03477165, 0.41887442, 0.51175784, 0.04519503],
       [0.65663956, 0.80924526, 0.48323266, 0.43282064]])

# Tensors

In [ ]:
Tx = torch.randn(3,4)
Tx

tensor([[-0.1754,  0.1760, -1.0991,  0.4880],
        [ 1.1560, -0.2691, -0.2976, -0.4227],
        [-2.2682,  1.7353,  1.7014,  0.7753]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## **Tensor Operations**

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Reshape if we don't know the number of items

my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_troch2 = my_torch2.reshape(5,-1)
print(my_troch2)
print(f'The shape of the array is {my_troch2.shape}')

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
The shape of the array is torch.Size([5, 2])


In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
print(my_torch4)
print(my_torch4.shape)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
torch.Size([2, 5])


In [ ]:
#Slices

my_torch7 = torch.arange(10)

In [ ]:
my_torch7[7]

tensor(7)

In [ ]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[0,:]

tensor([], size=(0, 2), dtype=torch.int64)

In [ ]:
# Return Column

my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [2]:
x  = torch.rand(4,4)
print(x)

tensor([[0.3391, 0.8899, 0.2798, 0.3930],
        [0.6496, 0.6308, 0.9376, 0.7742],
        [0.5302, 0.6267, 0.2340, 0.8682],
        [0.3399, 0.3853, 0.6121, 0.9025]])


In [10]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [11]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [12]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [17]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [18]:
d = torch.from_numpy(c)
d

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)